CREATE TABLE sleep_logs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT                 NOT NULL DEFAULT 1,
    date               DATE                   NOT NULL,
    bed_time           TIME WITHOUT TIME ZONE NOT NULL,
    wake_time          TIME WITHOUT TIME ZONE NOT NULL,
    total_time_minutes BIGINT                 NOT NULL,
    mood               VARCHAR(10)            NOT NULL CHECK (mood IN ('BAD', 'OK', 'GOOD'))
);
